app = "lp-lab"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8050"

[http_service]
  internal_port = 8050
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = 256
  cpu_kind = "shared"
  cpus = 1